#!groovy
pipeline {
  agent {
    label 'linux'
  }

  environment {
    SERVICE_NAME = 'cennznet-js'
    GIT_NAME = 'Jenkins'
    GIT_EMAIL = 'jenkins@centrality.ai'
    GIT_BRANCH = 'DK-5-Deployment-Pipeline'
    IMAGE_NAME = "centrality/${SERVICE_NAME}-build:1.0.${BUILD_NUMBER}"
    PUBLISH_IMAGE_NAME = "centrality/${SERVICE_NAME}:1.0.${BUILD_NUMBER}"
  }

  stages {
    stage('Build') {
      environment {
        SSH_RSA_FILE_PATH = credentials('jenkins-ssh-key')
      }
      when {
        equals expected: true,
        actual: false
      }
      steps {
        sh './ci/deployment/build.sh'
      }
    }
    stage('Unit Test') {
      when {
        equals expected: true,
        actual: false
      }
      steps {
        sh './ci/pr/unit-test.sh'
      }
    }
    stage('Confirm Publish') {
      when {
        equals expected: true,
        actual: false
      }
      steps {
        timeout(time:30, unit:'MINUTES') {
          input "Confirm publish?"
        }
      }
    }
    stage('Publish to Gemfury') {
      environment {
        GEMFURY_TOKEN = credentials('GEMFURY_TOKEN')
      }
      when {
        equals expected: true,
        actual: false
      }
      steps {
        sh './ci/deployment/publish.sh'
      }
    }
    stage('Publish Document') {
      when {
        equals expected: true,
        actual: false
      }
      steps {
        echo 'Publish to Readthedoc'
      }
    }
  }
}