// Copyright 2017-2021 @cennznet/api authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@cennznet/api', version: '2.0.0-alpha.4' };
